### ISSUE TITLE
Syncing between plex and Shoko Server

### ISSUE THREAD

**Issue by Cazzar** [Cazzar/ShokoMetadata.bundle#1]
Idea:

 - in Shoko we create a dummy Plex client that scrolls through a "section" (essentially library) and matches off anime series and marking as watched if watched on Shoko's side and syncing watch stats with Plex

**Comment by Cazzar** [comment]
https://github.com/ammmze/csharp-plex-api/

**Comment by hidden4003** [comment]
Looks like there is some JSON API while it is for sending commands to plex if you keep port open then you will get events. This would need support from shoko side.
https://forums.plex.tv/discussion/87050/send-play-pause-stop-events-to-my-app

Also webhooks for premium users.
https://support.plex.tv/hc/en-us/articles/115002267687

**Comment by Cazzar** [comment]
This will be released in next major shoko update.
