### ISSUE TITLE
optimize feature does not name season 0 & -1 files correctly.

### ISSUE THREAD

**Issue by CuddleBear92** [Cazzar/ShokoMetadata.bundle#10]
leaving this issue here to keep track of it in case someone gets a thought or something.
while this issue might not be fixable, I still think it's an issue that should stay up till it does work.

as of the time of writing the season 0 and season -1 (specials, OP/ED) files does not name itself correctly when saving their new transcoded file when using the plex optimize feature.

In my case, all files I had of those two season types was named "1900-01-01.mp4".
Since all the files got named the same name it replaced itself and overwrote itself as the new one was made.

This issue does not seem to happen at all with the normal episodes, which name itself correctly from the start with S1E3 or whatever.

note also normal tv episodes that do not use the shoko agent has this issue when I have used the feature.

**Comment by Cazzar** [comment]
Unfortunately there is nothing that I can do as this is a Plex issue.

Report the issue to Plex as I am using -1 as a stop-gap.
Also season 0 is the Plex native "Specials" directory

**Comment by CuddleBear92** [comment]
that's too bad, it's a great feature that some prob will use at some point with the agent. 

do still think the issue should be logged here, that's why I wrote it in the first place.

**Comment by Cazzar** [comment]
But what for? You noted in the discription it does not matter if the metadata agent is used?
