### ISSUE TITLE
Sync watched states

### ISSUE THREAD

**Issue by asmoranomar** [Cazzar/ShokoMetadata.bundle#11]
I'd like to say I tried, but I'm not really proficient in python or SQL, and I had a brief look at the Shoko API but I felt a bit overwhelmed and stopped there.  Maybe I'm going in way above my head and I'm making this far too complicated, but here we go.

Basically I don't see anywhere in your code that updates the watched states in Shoko.  This is probably due to the fact that the Scanner/Agent Framework doesn't seem to allow you intercept commands to flag a video as watched and also send it to Shoko.  Understandable, Scanner is for scanning and the Agent is for metadata.

However, I did stumble upon a tool that is used to sync watched states between Plex servers.  It basically syncs the `metadata_items_settings` table between servers.  I had a look at this table and it houses the metadata containers marked viewed, identified by metadata `guid`.  For this program, this is all that would be needed to sync the servers.

For Shoko however, you would need to resolve the container `guid `to an actual filename(s).  To do that, you would need to reference the table `metadata_items` and find the `id` or ids associated with the `guid` by using the query `SELECT id FROM metadata_items WHERE guid=""` (enter the guid into the query).  Once you have the metadata `id `or ids, you will then need to find the media `id `or ids.  To do this, you need to reference the `media_items`table and run the query `SELECT id FROM media_items WHERE metadata_item_id=""` (enter the metadata id(s) into the query).  Finally, once you have the media `id`, you can obtain the filename by running one more query on the table media_parts using `SELECT file FROM media_parts WHERE id=""` (enter the media id(s) into the query).  After that I assume you could query Shoko and find the anime and then mark it watched.  

The question remains, when should this occur?  Since we can't intercept the command for watched state, we have to come up with a new solution.  I recommend that this be done during `def Update()` or `def Scan()`.  If the user has the update library periodically selected, the scanner will run at the selected interval and the `def Scan()` option would run during that time.  Optionally, the update could be placed in the `def Update()` and the user could start an update by manually refreshing all metadata.  I'm sure you can see the pros and cons of each

Please note that the `guid` can actually reference multiple files - one of the examples I was looking at was a series with a special, and all the files were under one `guid`.  In fact, if i marked one as viewed, it marked all the videos as viewed.  I'm not sure why Plex does this.

Edit: [Here](https://github.com/fiLLLip/plex-watched-sync) is the link to the code I was talking about earlier.  It's licenced under Apache 2.0.

**Comment by Cazzar** [comment]
I have already written most of the syncing as part of ShokoServer itself, the closed issue #1 actually was my initial project to do so.

The current code-base has two implementations, 
Plex webhook: `http://localhost:8111/plex/` 
Bi-Directional sync as part of a miniaturized plex client.

If you want to discuss more, feel free to contact me on the #plex channel in the [Shoko discord.](https://discord.gg/ZbWZUqN)

**Comment by asmoranomar** [comment]
Ha! I knew I was over thinking it.  Glad your on top of it.

**Comment by Cazzar** [comment]
Yeah, syncing from plex side is kinda a pain, the only way of working out what is happening on it's side via official apis is web, or scanning logs.
