### ISSUE TITLE
Issue with anime with short titles

### ISSUE THREAD

**Issue by XellossMetallium** [Cazzar/ShokoMetadata.bundle#12]
Hi, I experienced problems in scraping anime with short titles. In particular such anime are mistakenly grouped with others that are correctly matched. 

For example:
Air and GTO were grouped with Konosuba season 2. 

If I issue plex a command to keep the series separate (by folder, I think), I get different entries of Konosuba s2.

If I try to manually link (in Plex) the aforementioned anime with their correct match Plex doesn't find the show at all (yet it is correctly scraped in Shoko). The correct title is not shown in the first list nor in the one I get by typing "Air" in the search box (I am talking about the section in the series level to "check link", not the master search of plex)

Thanks.

![image](https://cloud.githubusercontent.com/assets/6177535/26560083/069154c8-44b4-11e7-9730-63b5148d3057.png)

**Comment by Cazzar** [comment]
What setup is currently in use? Just the metadata agent or agent + scanner?

**Comment by Cazzar** [comment]
Because typically with the scanner in place the identification is dependent
on the filename, which Shoko is aware of

**Comment by XellossMetallium** [comment]
Shoko Series Scanner is installed and active alongside with ShokoTV agent. 
I noticed that if I try "Air" as keyword plex gives a long list of wrong results (the screenshot above) but, for example, if i use as keyword "Gekijouban", Plex finds "Gekijouban Air" (the movies, a separate group in Shoko). 
By logic the keyword "Air" should have shown at least "Gekijouban Air" since it is actually there, but since that was not the case I'd say that the issue is on the Plex side (or mine) while the scanner works as intended. But I'm no expert.

**Comment by Cazzar** [comment]
Can I get a screenshot of the advanced settings for the library in plex.
Just want an idea of the settings.

**Comment by XellossMetallium** [comment]
Sure 

![screenshot of plex 3](https://cloud.githubusercontent.com/assets/6177535/26570767/82c26dbc-4512-11e7-9f05-bb038eb592e9.png)
![screenshot of plex 2](https://cloud.githubusercontent.com/assets/6177535/26570765/82b9b366-4512-11e7-9dc7-8dd41deca834.png)
![screenshot of plex 1](https://cloud.githubusercontent.com/assets/6177535/26570766/82bc4874-4512-11e7-8d7a-e897474ee3f9.png)

**Comment by XellossMetallium** [comment]
Oh, I didn't notice the "fuzzy" setting. By disabling it I am now able to separate and correct the wrong links.
Can I ask what that option may do to produce that effect? Do I miss something useful by keeping it unchecked?

**Comment by Cazzar** [comment]
"fuzzy" searching was an early hack I implemented to ignore generally the characters you wouldn't have plex display, like invalid path characters in windows + `{}()-[]`

In the case of using the scanner, it should automatically be pulling the anime information from shoko to link it though, as it never needs to "match" with the data source.

In the case of Air for example, is there any matches that show 100 as the score? + does Air exist?

**Comment by XellossMetallium** [comment]
Well, now that I deactivated fuzzy searching I found Air, GTO and others with 100% accuracy. When I had it active you may refer to the screenshot in the first post to see the result: no Air at all and Konosuba at 85% (the same for GTO, hence my deduction about the short titles).

**Comment by Cazzar** [comment]
If your using the latest release, there may have been some bugs with the
fuzzy searching within Shoko, will be fixed on next release

**Comment by XellossMetallium** [comment]
Yes, I'm on 1.1.0. I'll wait for the next update to check and close the issue, then! 
Thank you!

**Comment by Cazzar** [comment]
Closing as I'm confident this is fixed, and 3.8 is out.

Reference: I have animes such as 18if and Air in my own collections
