### ISSUE TITLE
use Relation settings as Plex Collections?

### ISSUE THREAD

**Issue by CuddleBear92** [Cazzar/ShokoMetadata.bundle#13]
since we have no way to group up any series right now, its all in folders like they are saved and per AniDBID. 
to be able to pull the groups we have saved in Shoko already and set them as collections in plex. 
this will group up all the related series, if you can do this with the xml file you load from Shoko it would be great. 

do wonder if there should or could be a way to force update this on any side though (would force refresh metadata on plex get new collections and remove the old for example)

**Comment by Cazzar** [comment]
Isn't exposed in Plex APIs

**Comment by CuddleBear92** [comment]
closing since it can't be used then sadly
