### ISSUE TITLE
Libraries from PIP

### ISSUE THREAD

**Issue by Jimmyson** [Cazzar/ShokoMetadata.bundle#14]
Would you happen to know if libraries grabbed from the PIP repository work with these scripts?

Two libraries I think should be integrated are the following:
- Requests (http://docs.python-requests.org/en/master/)
- PlexAPI (https://pypi.python.org/pypi/PlexAPI)

Particularly the "Requests" library as it has a stronger process of creating HTTP requests.

**Comment by Cazzar** [comment]
The plex api for having dependancies, is either nonexistent or non-documented, i'd either need to include requests as a submodule and maintain that, or just use URLLib2  (which I am likely to do, as plex caching is a bitch)

As for PlexAPI, it's aimed audience is for things similar to PlexPy or Shoko's Plex watchstate sync,  it's essentially a plex client.

**Comment by Jimmyson** [comment]
Doing some digging online. It seems that Plex has a very limited Python configuration. PIP will have to be out of the question! This (which I believe you would have read) answers my question!
https://us.v-cdn.net/6025034/uploads/editor/cm/cojaep28kmq3.pdf
