### ISSUE TITLE
Cannot select Shoko Series Scanner

### ISSUE THREAD

**Issue by Terr4** [Cazzar/ShokoMetadata.bundle#20]
Hello,

It is mentioned that the bundle includes a "Shoko Series Scanner" and this one can/should be used instead of "Plex Series Scanner", however after installing the bundle I cannot select this scanner or see it in any options.

When I create a new library I select TV-Shows and under Advanced I see the following:

Scanner:
- Absolute Series Scanner
- Absolute Series Scanner (legacy)
- Plex Series Scanner

Agent:
- Personal Media Shows
- Hama TV
- TheTVDB
- ShokoTV
- The Movie Database

It seems "Plex Series Scanner" is missing from the Scanners.

**Comment by Terr4** [comment]
Ah nevermind, I found the solution on following announcement page.
But imho it should also be mentioned in the Docs on Github or on the ShokoMetadata description on the Shokoanime website.

https://shokoanime.com/announcing-a-new-plugin-shokometadata/

_We need to copy the file Contents/Resources/Series/Shoko Series Scanner.py out of this folder and into Plex Media Server/Scanners/Series creating the directory if necessary.
do note we also need to make sure we edit the Prefs array in this scanner file to point towards the Shoko Server._

**Comment by Cazzar** [comment]
https://github.com/Cazzar/ShokoMetadata.bundle/blob/master/README.md#notes

**Comment by Cazzar** [comment]
```
I recommend installing the Shoko Series scanner into the `Scanners/Series` folder for better compatibility.
```

The actual folder varies by installation and distribution.
