### ISSUE TITLE
Incorrect season/episode for Bakemonogatari

### ISSUE THREAD

**Issue by hidden4003** [Cazzar/ShokoMetadata.bundle#23]
12 Episodes from tvdb and anidb match then, 13-15 from tvdb are listed as Specials 1-3 currently it seems metadata takes season from tvdb but episode number from shoko.

![image](https://user-images.githubusercontent.com/197087/36154236-71e35284-10d9-11e8-9736-169b7c96582d.png)
![image](https://user-images.githubusercontent.com/197087/36154591-a0b389fc-10da-11e8-834f-4cb74d87ceb0.png)

Log of the scanner, code is from latest master branch
`path: [Hi10]_Bakemonogatari_[BD_720p]
files: ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_01_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_02_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_03_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_04_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_05_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_06_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_07_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_08_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_09_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_10_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_11_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_12_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_13_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_14_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_15_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_ED1_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_ED2_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_OP1_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_OP2_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_OP3a_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_OP3b_(BD_720p)_(Coalgirls).mkv', 'E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_OP4_(BD_720p)_(Coalgirls).mkv']
mediaList: []
subdirs: []
language: en
root: E:\Anime
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_01_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_01_%28BD_720p%29_%28Coalgirls%29.mkv
Got API KEY: 5b265e63-49b2-4592-a908-46efe6d568de
Requesting: api/serie/fromep?id=1459&nocast=1&notag=1
show title: Bakemonogatari
season number: 1
episode number: 1
vid: Bakemonogatari (season 1, episode: 1) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_02_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_02_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1460&nocast=1&notag=1
show title: Bakemonogatari
season number: 1
episode number: 2
vid: Bakemonogatari (season 1, episode: 2) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_03_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_03_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1461&nocast=1&notag=1
show title: Bakemonogatari
season number: 1
episode number: 3
vid: Bakemonogatari (season 1, episode: 3) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_04_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_04_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1462&nocast=1&notag=1
show title: Bakemonogatari
season number: 1
episode number: 4
vid: Bakemonogatari (season 1, episode: 4) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_05_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_05_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1463&nocast=1&notag=1
show title: Bakemonogatari
season number: 1
episode number: 5
vid: Bakemonogatari (season 1, episode: 5) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_06_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_06_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1465&nocast=1&notag=1
show title: Bakemonogatari
season number: 1
episode number: 6
vid: Bakemonogatari (season 1, episode: 6) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_07_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_07_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1464&nocast=1&notag=1
show title: Bakemonogatari
season number: 1
episode number: 7
vid: Bakemonogatari (season 1, episode: 7) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_08_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_08_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1469&nocast=1&notag=1
show title: Bakemonogatari
season number: 1
episode number: 8
vid: Bakemonogatari (season 1, episode: 8) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_09_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_09_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1468&nocast=1&notag=1
show title: Bakemonogatari
season number: 1
episode number: 9
vid: Bakemonogatari (season 1, episode: 9) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_10_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_10_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1467&nocast=1&notag=1
show title: Bakemonogatari
season number: 1
episode number: 10
vid: Bakemonogatari (season 1, episode: 10) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_11_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_11_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1474&nocast=1&notag=1
show title: Bakemonogatari
season number: 1
episode number: 11
vid: Bakemonogatari (season 1, episode: 11) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_12_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_12_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1475&nocast=1&notag=1
show title: Bakemonogatari
season number: 1
episode number: 12
vid: Bakemonogatari (season 1, episode: 12) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_13_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_13_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1477&nocast=1&notag=1
show title: Bakemonogatari
season number: 1
episode number: 1
vid: Bakemonogatari (season 1, episode: 1) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_14_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_14_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1492&nocast=1&notag=1
show title: Bakemonogatari
season number: 1
episode number: 2
vid: Bakemonogatari (season 1, episode: 2) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_15_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_15_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1498&nocast=1&notag=1
show title: Bakemonogatari
season number: 1
episode number: 3
vid: Bakemonogatari (season 1, episode: 3) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_ED1_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_ED1_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1471&nocast=1&notag=1
show title: Bakemonogatari
season number: -1
episode number: 8
vid: Bakemonogatari (season -1, episode: 8) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_ED2_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_ED2_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1486&nocast=1&notag=1
show title: Bakemonogatari
season number: -1
episode number: 10
vid: Bakemonogatari (season -1, episode: 10) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_OP1_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_OP1_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1470&nocast=1&notag=1
show title: Bakemonogatari
season number: -1
episode number: 2
vid: Bakemonogatari (season -1, episode: 2) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_OP2_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_OP2_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1473&nocast=1&notag=1
show title: Bakemonogatari
season number: -1
episode number: 3
vid: Bakemonogatari (season -1, episode: 3) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_OP3a_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_OP3a_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1476&nocast=1&notag=1
show title: Bakemonogatari
season number: -1
episode number: 4
vid: Bakemonogatari (season -1, episode: 4) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_OP3b_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_OP3b_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1506&nocast=1&notag=1
show title: Bakemonogatari
season number: -1
episode number: 5
vid: Bakemonogatari (season -1, episode: 5) => [] starting at 0
file: E:\Anime\[Hi10]_Bakemonogatari_[BD_720p]\(Hi10)_Bakemonogatari_-_OP4_(BD_720p)_(Coalgirls).mkv
Requesting: api/ep/getbyfilename?filename=%28Hi10%29_Bakemonogatari_-_OP4_%28BD_720p%29_%28Coalgirls%29.mkv
Requesting: api/serie/fromep?id=1502&nocast=1&notag=1
show title: Bakemonogatari
season number: -1
episode number: 7
vid: Bakemonogatari (season -1, episode: 7) => [] starting at 0
stack media
media list [Bakemonogatari (season 1, episode: 1) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_01_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season 1, episode: 2) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_02_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season 1, episode: 3) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_03_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season 1, episode: 4) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_04_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season 1, episode: 5) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_05_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season 1, episode: 6) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_06_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season 1, episode: 7) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_07_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season 1, episode: 8) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_08_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season 1, episode: 9) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_09_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season 1, episode: 10) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_10_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season 1, episode: 11) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_11_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season 1, episode: 12) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_12_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season 1, episode: 1) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_13_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season 1, episode: 2) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_14_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season 1, episode: 3) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_15_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season -1, episode: 8) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_ED1_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season -1, episode: 10) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_ED2_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season -1, episode: 2) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_OP1_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season -1, episode: 3) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_OP2_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season -1, episode: 4) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_OP3a_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season -1, episode: 5) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_OP3b_(BD_720p)_(Coalgirls).mkv'] starting at 0, Bakemonogatari (season -1, episode: 7) => ['E:\\Anime\\[Hi10]_Bakemonogatari_[BD_720p]\\(Hi10)_Bakemonogatari_-_OP4_(BD_720p)_(Coalgirls).mkv'] starting at 0]`

**Comment by Cazzar** [comment]
![image](https://user-images.githubusercontent.com/994214/36311121-53d6c832-137e-11e8-9a2e-61ac42de375f.png)
try with latest devel, issue seems fixed.

**Comment by Cazzar** [comment]
Closing, if this is still an issue let me know
