### ISSUE TITLE
Series Scanner assumes Server is on localhost.

### ISSUE THREAD

**Issue by Remnence** [Cazzar/ShokoMetadata.bundle#28]
Could you update the scanner to pull the server location from the ShokoTV MetaData settings? Or failing that update the readme on the frontpage of this repo? The scanner fails to operate if it cannot find the server.

**Comment by Cazzar** [comment]
Because of how the Plex API is, there is no way to do this.
Proper documentation is in the middle of being written.

**Comment by Cazzar** [comment]
Closing right now as no way to fix that requires knowing some sort of authentication to plex.
Which at that point, you might as well use the same method we have right now.
