### ISSUE TITLE
For some series, series posters are used for all episode thumbs, and related issues

### ISSUE THREAD

**Issue by purposelycryptic** [Cazzar/ShokoMetadata.bundle#29]
I am not sure what the exact conditions required for this to occur are, but, for most (but not all) of my series, ShokoMetadata assigns the series posters as the thumb for all episodes, i.e.:
![Imgur](https://i.imgur.com/fscgdve.jpg)

It seems to pull all the series posters too, not just the currently chosen one:
![Imgur](https://i.imgur.com/hOuZfxs.jpg)

It does also provide an actual thumb (in the lowest priority position), but it appears to be a system-generated one, vs one from Shoko or TheTVDB:
![Imgur](https://i.imgur.com/8FEZOkt.jpg)

For comparison:
![Imgur](https://i.imgur.com/326Aq9o.jpg)

Curiously, it seems to pull no posters whatsoever for the individual seasons themselves:
![Imgur](https://i.imgur.com/2vb6mUp.jpg)

Despite both season and series posters being available on TheTVDB (and through it, Shoko), of which it would normally assign one, the other or both of:
![Imgur](https://i.imgur.com/McImXn5.jpg)

Instead, it defaults to whatever is set as the series poster at the moment, and changes as soon as the series poster is changed (while the episode thumb remains set to whatever poster it was initially assigned).

------------------------------------------------------------------------------------------------------------
I have tried setting both 'Use shoko's thumbnails' and the various options for displaying seasons in every possible combination, refreshing metadata, unmatching/rematching series, and deleting/recreating the library, deleting/reinstalling ShokoMetadata, but with no luck. 

All of this was done using ShokoTV as Agent and Shoko Series Scanner as Scanner. 
Out of curiosity I tested creating a new library using ShokoTV as Agent, but HAMA's Absolute Series Scanner as Scanner, and the exact same issues occurred (including the one at the end of this post), so the issue definitely seems to be the agent.

------------------------------------------------------------------------------------------------------------
All my series files and folders use the main AniDB name, and episodes are numbered according to AniDB; my Folder Structure is very simple, since trying to use season folders with ShokoMetadata in the past (after migrating from Emby) resulted in strange issues and false matches. 

Here is an example of my current setup:

-\Anime
-------->\Yuru Yuri [Doki] [BD, 1080p]
----------------------------------------->\Yuru Yuri - 01 [Doki] [BD, 1080p, FLAC] [2CC465FE].mkv
----------------------------------------->\Yuru Yuri - 02v2 [Doki] [BD, 1080p, FLAC] [394E392B].mkv
----------------------------------------->\etc.
----------------------------------------->\Yuru Yuri - C1 [Doki] [BD, 1080p, FLAC] [EC7BE858].mkv
----------------------------------------->\Yuru Yuri - S1 [Doki] [BD, 1080p, FLAC] [CEC491E6].mkv

All episodes are properly identified and organized within Plex - just with the episode thumbnails all messed up and season posters not being pulled for most series. Additionally, and I'm not sure if this is a bug or simply working as intended, but none of the series posters and fanart match the ones actually being used in Shoko - it seems to pull the same set shoko has downloaded, but always use a completely different image from that set.

------------------------------------------------------------------------------------------------------------
Honestly the most confusing part about this is that, for some series, all images are properly fetched; if all were incorrect, I would simply assume that the wrong variable was accidentally assigned, which would be easy to fix, but the fact that it occasionally works correctly throws that theory out the window. 

On those where it works properly, season and special folder posters are also properly pulled, for example:
![Imgur](https://i.imgur.com/XNAuvyB.jpg)

------------------------------------------------------------------------------------------------------------
At first I thought it might be an issue of a series having a season for which there were no image files to use, but even those with all the necessary images (Like 'Akame ga Kill!') still have the same issue...

------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------
Also, and I'm not sure if this issue is related, or entirely separate, but certain specific series will always pull images from an entirely different series at highest priority, despite those images not existing in Shoko - for example:
![Imgur](https://i.imgur.com/zO9eKSR.jpg)
![Imgur](https://i.imgur.com/tA8u0xK.jpg)
It always only pulls one image per category from a different series, always from the same different series, and the rest of the images pulled are all normal.

**Comment by Cazzar** [comment]
The images api in shoko is a little bit to be improved.
if you're able I would suggest jumping on the shoko discord and pinging me in the #plex channel in ~7h so I can help looking into it live, with a bit of manual troubleshooting.

Thanks for the detailed report, helps with knowing what's happening

**Comment by Cazzar** [comment]
Image counts seem to show multiple for me as of late.
The image assignment has yet to be fixed, though that's ultimately upstream, so specific to Shoko, so best to create the issue there.

Images should ultimately be assigned to at a "Series" level, and maybe a common one for the Group then allow the API to show what's specific for the user.
