### ISSUE TITLE
release year fails to display

### ISSUE THREAD

**Issue by CuddleBear92** [Cazzar/ShokoMetadata.bundle#31]
The release year fails to display in ui correct even though the year is in place in the `originally available`
attached screenshots.

![46086435-5df7fd80-c1a8-11e8-826e-70414d112a07](https://user-images.githubusercontent.com/8496821/46095508-03b56780-c1bd-11e8-9b23-ba99181779e2.png)![46086436-5df7fd80-c1a8-11e8-860f-5db1fec6aa12](https://user-images.githubusercontent.com/8496821/46095514-06b05800-c1bd-11e8-9998-bc104a8bedaa.png)![46086442-62bcb180-c1a8-11e8-8b82-5b89a6744f52](https://user-images.githubusercontent.com/8496821/46095524-0adc7580-c1bd-11e8-9b72-31783f783e96.png)![46086443-63554800-c1a8-11e8-828c-1fe35f83325e](https://user-images.githubusercontent.com/8496821/46095530-0ca63900-c1bd-11e8-9d65-7c6743b3fff4.png)

**Comment by Cazzar** [comment]
Just going through some old issues.

seems to be shown fine on where the data is passed from Shoko.
