### ISSUE TITLE
Series/Episode Summary Cleaning

### ISSUE THREAD

**Issue by purposelycryptic** [Cazzar/ShokoMetadata.bundle#34]
I just noticed that activity seems to have restarted on this (I've sadly been to busy being seriously sick for the last while now to keep up with Shoko development, but I'm guessing this means the whole rebuild/.Net2.0 operation has seen major progress).

I noticed a commit for removing the URLs from AniDB series summaries, and thought I'd mention that my fork (minimalistic as the progress I made on it was) has functions for also removing other unneeded text, such as series premiere information, source citations for the summary, and those long "*Based on....* lines that take up a large part of the series summary field in Plex. 

I originally put it together for HAMA, but RegEx is RegEx, and it worked fine in testing - I used it in my library of 1,600+ series, and it got pretty much everything (Though the guys working on HAMA apparently just put together an improved version a few days ago, so they might be worth looking into too).

It also has a separate cleaning function for AniDB episode summaries, since almost all of them are now added via a bot that pulls them from Crunchyroll, and adds the line "Source: Crunchyroll" to the end of each and every one, which gets pretty annoying.

Anyway, I just wanted to mention it - in case you want to use it, I'd be happy to set it get used.

Looking forward to checking out Shoko again, once I can actually get out of bed and back to normal life 🙂

**Comment by Cazzar** [comment]
I'm happy to accept pull requests against the devel branch if you want to
help.

There's a lot planned in the back of Shoko which will be taking months to
do further.

I would suggest hiding each change in am option instead of just straight up
making the changes.

**Comment by purposelycryptic** [comment]
I'm sadly currently in the middle of a severe case of Pneumonia, and between the fever and barely being able to breathe, anything requiring proper focus is unfortunately beyond me for the moment; if someone else hasn't already looked into it by the time I'm back on my feet, I'll be happy to do so, but, given my doctor just scheduled me for an MRI next week because he thinks I might have an additional secondary condition, I honestly have no clue when that might be. :-/

**Comment by Cazzar** [comment]
https://github.com/Cazzar/ShokoMetadata.bundle/commit/ec4d960c91d1ef19742fb67a8f325a4cf1302542
