### ISSUE TITLE
Files in subdirectory get detected as parent series

### ISSUE THREAD

**Issue by Cazzar** [Cazzar/ShokoMetadata.bundle#4]
When using the scanner files in the subdirectory will get merged down into the parent series

For example if we have:
`/To Heart/Files....` and `/To Heart/To Heart 2/.....`

everything in `To Heart 2` will be a duplicate in `To Heart`

![chrome_2017-03-06_21-42-59](https://cloud.githubusercontent.com/assets/994214/23609738/9a60d422-02c3-11e7-9e12-c96c15f38c38.png)

**Comment by hidden4003** [comment]
My structure was:

```
K-On Collection\
K-On Collection\movie.mkv
K-On Collection\K-On season 1\
K-On Collection\K-On season 2\
```
But Plex would only create 1 show in the library, and in my case it would get detected as K-On!!, that is Season 2 and not the parent, which is K-On movie.

My guess is that Plex gets stuck when encounters a file so shortest path becomes series and other subfolders get ignored, if metadata agent provides different show names it just gets overwritten so I guess the last processed file sets the title.

**Comment by Cazzar** [comment]
d0b49c6c4478bc73cf45bff38b846235c11e7739
