### ISSUE TITLE
Directories with Similar Names treated as same series

### ISSUE THREAD

**Issue by Jimmyson** [Cazzar/ShokoMetadata.bundle#7]
Two series with a similar name are merged into one.
`.../Anime/[DATS] Ryuusei no Rockman Tribe/`
`.../Anime/[DATS] Ryuusei no Rockman/`

Whilst these series are related, they are identified as separate series according to Shoko and AniDB.
Would this be the result of the fuzzy search?

![image](https://cloud.githubusercontent.com/assets/8276052/24915973/181429ae-1f1c-11e7-957b-6499e1d03e1d.png)

**Comment by Cazzar** [comment]
@Jimmyson If you think it is fuzzy search turn it off.
Also, if you scan those two directories without using the metadata agent, are they created separate or together?

**Comment by Jimmyson** [comment]
Scanning with another agent seems t merge the two (so my assumption may be wrong).
But sadly I can't prove as ShokoMetadata seems to fail with scanning a new library.

**Comment by Cazzar** [comment]
I'd need Scanner logs to work out further.

**Comment by Jimmyson** [comment]
This was user error. Not a ShokoMetadata error!
