### ISSUE TITLE
load all art from shoko

### ISSUE THREAD

**Issue by CuddleBear92** [Cazzar/ShokoMetadata.bundle#9]
only a few covers and fanart images gets loaded into plex and its edit menu. 
personally think it should load everything it can.

refreshing series in plex will let it load new images too it seems, so people could spam the refresh button to gain more images that way. but we really shouldnt have too. 

also noted that it only loads the anidb cover art and nothing else. think this is a missed opportunity.

made an issue on Shoko Server aswell: https://github.com/japanesemediamanager/ShokoServer/issues/631

**Comment by Cazzar** [comment]
The code currently iterates through all options given from Shoko's API and
assigns it via that, the delay may simply just be Shoko not having it
downloaded yet.

**Comment by CuddleBear92** [comment]
even if its all on the shoko side from the start and the plex library was only made when most were already in place? 

even if I delete the series on plex, or even refreshing all metadata (which should redownload all metadata) does not fix it.

**Comment by Cazzar** [comment]
When the metadata is re downloaded, cover-art is coded all here: https://github.com/Cazzar/ShokoMetadata.bundle/blob/62cc040459d94cc0638e9ad897bd3f0abb106501/Contents/Code/__init__.py#L95-L106

**Comment by CuddleBear92** [comment]
not that thumbs does not get loaded at all either aswell as banners.

**Comment by Cazzar** [comment]
![image](https://user-images.githubusercontent.com/994214/27261620-2a460cac-548a-11e7-9d29-916a18ce553f.png)

The issue itself is part of the Shoko Server API not the Agent

**Comment by Cazzar** [comment]
This has since been fixed, will work properly with 3.8
